import nodemailer from 'nodemailer'
import type { TradeSetup } from '@/types/ai'
import { formatPrice } from '@/lib/utils'

function getTransporter() {
  return nodemailer.createTransport({
    host: process.env.SMTP_HOST ?? 'smtp.gmail.com',
    port: parseInt(process.env.SMTP_PORT ?? '587'),
    secure: false,
    auth: {
      user: process.env.SMTP_USER,
      pass: process.env.SMTP_PASS,
    },
  })
}

function buildSignalHtml(setup: TradeSetup, analysis: string): string {
  const dirColor = setup.direction === 'long' ? '#089981' : '#F23645'
  const dirLabel = setup.direction.toUpperCase()
  const confBar = Math.round(setup.confidence)

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: Inter, Arial, sans-serif; background: #0F1117; color: #D1D4DC; margin: 0; padding: 20px; }
    .container { max-width: 600px; margin: 0 auto; }
    .header { background: #1B1F2E; border-radius: 12px; padding: 24px; margin-bottom: 16px; border: 1px solid #2D3148; }
    .badge { display: inline-block; padding: 6px 16px; border-radius: 6px; font-weight: 700; font-size: 18px; background: ${dirColor}22; color: ${dirColor}; border: 1px solid ${dirColor}; }
    .symbol { font-size: 28px; font-weight: 800; color: #fff; }
    .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin: 16px 0; }
    .card { background: #1B1F2E; border: 1px solid #2D3148; border-radius: 8px; padding: 16px; }
    .label { font-size: 11px; color: #787B86; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 4px; }
    .value { font-size: 20px; font-weight: 700; color: #fff; font-family: monospace; }
    .conf-bar { background: #2D3148; border-radius: 4px; height: 8px; margin-top: 8px; }
    .conf-fill { background: ${confBar >= 70 ? '#089981' : confBar >= 50 ? '#F7C545' : '#F23645'}; height: 8px; border-radius: 4px; width: ${confBar}%; }
    .analysis { background: #1B1F2E; border: 1px solid #2D3148; border-radius: 8px; padding: 16px; white-space: pre-wrap; font-size: 14px; line-height: 1.6; }
    .footer { text-align: center; color: #787B86; font-size: 12px; margin-top: 24px; }
    .accent { color: #2962FF; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <div class="badge">${dirLabel}</div>
      <div class="symbol">${setup.symbol}</div>
      <p style="color:#787B86; margin:8px 0 0">Generated by TechnoBiz Trader AI · ${new Date(setup.generatedAt).toUTCString()}</p>
    </div>

    <div class="grid">
      <div class="card">
        <div class="label">Entry Price</div>
        <div class="value accent">$${formatPrice(setup.entry)}</div>
      </div>
      <div class="card">
        <div class="label">Stop Loss</div>
        <div class="value" style="color:#F23645">$${formatPrice(setup.stopLoss)}</div>
      </div>
      ${setup.takeProfit.map((tp, i) => `
      <div class="card">
        <div class="label">Take Profit ${i + 1}</div>
        <div class="value" style="color:#089981">$${formatPrice(tp)}</div>
      </div>`).join('')}
      <div class="card">
        <div class="label">Risk/Reward</div>
        <div class="value">1:${setup.riskReward.toFixed(2)}</div>
      </div>
    </div>

    <div class="card" style="margin-bottom:16px">
      <div class="label">Confidence Score — ${setup.confidence}%</div>
      <div class="conf-bar"><div class="conf-fill"></div></div>
    </div>

    <div class="analysis">${analysis.substring(0, 1500)}</div>

    <div class="footer">
      <p>TechnoBiz Trader AI · Institutional Grade Market Analysis</p>
      <p>This is not financial advice. Trade at your own risk.</p>
    </div>
  </div>
</body>
</html>`
}

export interface SendSignalOptions {
  to: string
  setup: TradeSetup
  analysis: string
  screenshotBase64?: string
}

export async function sendSignalEmail(opts: SendSignalOptions): Promise<{ success: boolean; error?: string }> {
  try {
    const transporter = getTransporter()
    const subject = `🎯 ${opts.setup.direction.toUpperCase()} Signal: ${opts.setup.symbol} — Confidence ${opts.setup.confidence}%`

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const attachments: any[] = []
    if (opts.screenshotBase64) {
      attachments.push({
        filename: `chart-${opts.setup.symbol}.png`,
        content: Buffer.from(opts.screenshotBase64, 'base64'),
        contentType: 'image/png',
        cid: 'chart@technobiz',
      })
    }

    await transporter.sendMail({
      from: process.env.EMAIL_FROM ?? 'TechnoBiz Trader AI <technobiztrader@gmail.com>',
      to: opts.to,
      subject,
      html: buildSignalHtml(opts.setup, opts.analysis),
      attachments,
    })

    return { success: true }
  } catch (err) {
    return { success: false, error: String(err) }
  }
}
